#!/usr/bin/env node
const fs = require('fs')
const forEach = require('async-foreach').forEach

let all = {}
let allData = {}

fs.readdir('tags/', function (err, files) {
  forEach(files, function (file) {
    let m = file.match(/^(.*)\.json$/)
    if (!m) {
      return
    }

    let done = this.async()

    fs.readFile('tags/' + file, (err, contents) => {
      let data

      try {
        data = JSON.parse(contents)
      } catch (e) {
        return done()
      }

      if (!data) {
        return done()
      }

      var ret = {}
      var keys = Object.keys(data)
      keys.sort()

      for (var i = 0; i < keys.length; i++) {
        ret[keys[i]] = data[keys[i]]
      }

      fs.writeFile('tags/' + file, JSON.stringify(ret, null, '    ') + '\n', done)
    })
  },
  allDone)
})

function allDone () {
}
